# .air.toml
[build]
# Command to build your Go application; adjust to include the /src directory
cmd = "sh -c '/app/local-test-runner.sh & cd src && go build . -o ../tmp/main'"

# The output binary location
bin = "./tmp/main"

# Directories and files to watch for changes
include_dir = ["src"]

# File extensions to watch
include_ext = ["go", "html", "css", "js"]

# Exclude directories
exclude_dir = ["tmp", "vendor"]

[log]
level = "debug"
